# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e16cf624d7bc08d020980ffb529ddb948ad907c457c9536e80fc48715fca4f355e9d72d7a19a4ba7291f078be3938292376103f79f963c0b38cfc938efd4e4

test:
  secret_key_base: 5b4cf6c099bdaf0d0f6a5c17cd4de1e0ee3ea33212edf5e21a50c6c711f7ea45367b49061b6fe4b3ddc1a791dd8c6703427f4050986232c74acbff3ae6dc9fb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
